// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUfNeo7sTTI3YalVLiFEVCSwQcCduBv4g',
    appId: '1:1030149444131:web:4604f0a2491305fa391796',
    messagingSenderId: '1030149444131',
    projectId: 'calorie-ai-app-978f8',
    authDomain: 'calorie-ai-app-978f8.firebaseapp.com',
    storageBucket: 'calorie-ai-app-978f8.firebasestorage.app',
    measurementId: 'G-GLDBXSE04N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpGlMx-YERFzrSzbZAItQqA_avWtZoiBk',
    appId: '1:1030149444131:android:aa754142fc72bf06391796',
    messagingSenderId: '1030149444131',
    projectId: 'calorie-ai-app-978f8',
    storageBucket: 'calorie-ai-app-978f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3Lg-1l0g5OABnjc5dN1ieZxTkYlJNqk',
    appId: '1:1030149444131:ios:051341200a2e93a8391796',
    messagingSenderId: '1030149444131',
    projectId: 'calorie-ai-app-978f8',
    storageBucket: 'calorie-ai-app-978f8.firebasestorage.app',
    iosBundleId: 'com.example.calorieAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA3Lg-1l0g5OABnjc5dN1ieZxTkYlJNqk',
    appId: '1:1030149444131:ios:051341200a2e93a8391796',
    messagingSenderId: '1030149444131',
    projectId: 'calorie-ai-app-978f8',
    storageBucket: 'calorie-ai-app-978f8.firebasestorage.app',
    iosBundleId: 'com.example.calorieAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUfNeo7sTTI3YalVLiFEVCSwQcCduBv4g',
    appId: '1:1030149444131:web:d4d82be929c05703391796',
    messagingSenderId: '1030149444131',
    projectId: 'calorie-ai-app-978f8',
    authDomain: 'calorie-ai-app-978f8.firebaseapp.com',
    storageBucket: 'calorie-ai-app-978f8.firebasestorage.app',
    measurementId: 'G-0Y62VZCVHE',
  );
}
